"""Pydantic schemas for AgroAI request and response contracts."""

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class SoilInput(BaseModel):
    """Input payload describing soil nutrients and optional climate/location."""

    # Soil nitrogen level in kg/ha.
    N: float = Field(..., ge=0, le=200, description="Nitrogen level in kg/ha")
    # Soil phosphorus level in kg/ha.
    P: float = Field(..., ge=0, le=200, description="Phosphorus level in kg/ha")
    # Soil potassium level in kg/ha.
    K: float = Field(..., ge=0, le=300, description="Potassium level in kg/ha")
    # Soil acidity/alkalinity scale from 0 to 14.
    ph: float = Field(..., ge=0, le=14, description="Soil pH value")
    # Ambient temperature in Celsius; optional for basic recommendations.
    temperature: Optional[float] = Field(
        default=None,
        ge=-10,
        le=60,
        description="Ambient temperature in Celsius",
    )
    # Relative humidity percentage; optional for basic recommendations.
    humidity: Optional[float] = Field(
        default=None,
        ge=0,
        le=100,
        description="Relative humidity percentage",
    )
    # Latitude used for weather-aware recommendation endpoint.
    latitude: Optional[float] = Field(
        default=None,
        description="Latitude coordinate for weather lookup",
    )
    # Longitude used for weather-aware recommendation endpoint.
    longitude: Optional[float] = Field(
        default=None,
        description="Longitude coordinate for weather lookup",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "N": 90.0,
                "P": 42.0,
                "K": 43.0,
                "ph": 6.5,
                "temperature": 28.0,
                "humidity": 82.0,
                "latitude": 17.3850,
                "longitude": 78.4867,
            }
        }
    )


class FertilizerRecommendation(BaseModel):
    """Single fertilizer recommendation item."""

    # Fertilizer product name.
    name: str = Field(..., description="Recommended fertilizer name")
    # Recommended amount with unit string.
    amount: str = Field(..., description='Application amount (e.g. "40 kg/acre")')
    # Explanation of why this fertilizer is recommended.
    reason: str = Field(..., description="Reason for recommendation")
    # Brand/product name (optional).
    brand: Optional[str] = Field(default=None, description="Fertilizer brand/product name")
    # Purchase link (optional).
    purchase_link: Optional[str] = Field(default=None, description="Link to purchase this fertilizer")


class CropRecommendation(BaseModel):
    """Predicted crop with confidence and alternative crop options."""

    # Top predicted crop name.
    crop: str = Field(..., description="Recommended crop name")
    # Model confidence score from 0 to 1.
    confidence: float = Field(..., ge=0, le=1, description="Prediction confidence")
    # Top three alternative crop suggestions.
    alternatives: List[str] = Field(
        ...,
        description="Three alternative crops ranked after the top prediction",
    )


class SoilAnalysis(BaseModel):
    """Interpreted nutrient and pH analysis with aggregate soil health score."""

    # Nitrogen level category (Low/Medium/High).
    n_level: str = Field(..., description="Nitrogen status: Low, Medium, or High")
    # Phosphorus level category (Low/Medium/High).
    p_level: str = Field(..., description="Phosphorus status: Low, Medium, or High")
    # Potassium level category (Low/Medium/High).
    k_level: str = Field(..., description="Potassium status: Low, Medium, or High")
    # pH classification (Acidic/Neutral/Alkaline).
    ph_status: str = Field(..., description="Soil pH status")
    # Numeric soil health score from 0 to 100.
    health_score: float = Field(..., ge=0, le=100, description="Soil health score")
    # Label derived from health score (Poor/Fair/Good/Excellent).
    health_label: str = Field(..., description="Soil health label")


class RecommendResponse(BaseModel):
    """Complete API response for crop recommendation endpoints."""

    # Overall soil analysis details.
    soil_analysis: SoilAnalysis = Field(..., description="Computed soil analysis")
    # Crop prediction and alternatives.
    crop_recommendation: CropRecommendation = Field(
        ...,
        description="Primary crop recommendation",
    )
    # Fertilizer adjustments based on nutrient gaps.
    fertilizer_plan: List[FertilizerRecommendation] = Field(
        ...,
        description="List of fertilizer recommendations",
    )
    # Advisory or warning messages generated by business logic.
    alerts: List[str] = Field(..., description="Warnings and advisory messages")
    # Indicates whether weather API data was used.
    weather_used: bool = Field(
        ...,
        description="Whether weather data was used in recommendation flow",
    )

